### ISSUE TITLE
Better error message on network dashboard the backend is not reachable

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-network-dashboard#68] opened 2021-09-22 08:49 UTC
-- _**Conclusion after discussion with @abizjak: Better error message on network dashboard the backend is not reachable**_ --

**Bug Description**
Wrong display of transaction lookup for multisig transaction that is not finalized yet:
![dashboard_multisig transfer](https://user-images.githubusercontent.com/69570978/134312173-a242c968-2aa6-45c2-9b28-64a7515c67c1.JPG)

After few seconds, probably after transaction is finalized, the display is correct:
![dashboard_multisig transfer_2](https://user-images.githubusercontent.com/69570978/134312201-166a3a33-299d-4a59-832c-c180d1b9a2ae.JPG)

transaction hash: `009ee4b5680de1234c4c5a2f1d9ac59d487642df1e0eba2803842d59513fc212`

**Steps to Reproduce**
- made multisig simple transfer in desktop wallet
- copied&pasted transaction hash quickly in network dashboard > transaction lookup
- enter

**Expected Result**
Transaction not finalized or sth similar.

**Actual Result**
See above.

**Versions**
- Network dashboard 1.0.1
- DW 1.2.0
- Chrome

**Comment by abizjak** [comment] 2021-09-22 09:16
I cannot reproduce this, I can get all the different states ("received", "committed", "finalized") without errors. I'm wondering whether there were updates in the backend that cause this intermittent issue.

**Comment by concordium-cl** [comment] 2021-09-22 12:15
Cannot reproduce in same setting neither. Let's call it a backend hiccup then.

**Comment by abizjak** [comment] 2021-09-22 12:21
One thing that might be worth fixing is that the network dashboard displays a friendlier error message in such a case.

So maybe you want to reopen this with that in mind.

**Comment by concordium-cl** [comment] 2021-09-22 12:24
Do we know what case it is? Or do you mean a general "connection lost" or similar?

**Comment by abizjak** [comment] 2021-09-22 13:08
I mean the general case where the backend is not reachable for some reason. The error should not be the raw thing you have on the screenshot, but something nicer such as "error querying transaction status" or similar.

**Comment by concordium-cl** [comment] 2021-09-22 13:16
Change error message acc. to previous comment.

**Closed** 2021-10-04 06:15 UTC
Labels: [Prio] Low, [Type] Bug, [Sev] Low
